botToken: TELEGRAM_BOT_TOKEN
refreshTime: 60
products:
      - 
        name: "5900x"
        url: "https://www.digitec.ch/fr/s1/product/amd-ryzen-9-5900x-am4-370ghz-12-core-processeurs-13987917"
      - 
        name: "5950x"
        url: "https://www.digitec.ch/fr/s1/product/amd-ryzen-9-5950x-am4-340ghz-16-core-prozessor-13987916?tagIds=76"
      - 
        name: "3080 Asus STRIX OC"
        url: "https://www.digitec.ch/fr/s1/product/asus-geforce-rog-strix-rtx-3080-o10g-gaming-10go-cartes-graphiques-13751783"
      - 
        name: "3080 Asus STRIX"
        url: "https://www.digitec.ch/fr/s1/product/asus-geforce-rog-strix-rtx-3080-10g-gaming-10gb-grafikkarte-13751736"
      - 
        name: "3080 MSI Ventus OC"
        url: "https://www.digitec.ch/fr/s1/product/msi-geforce-rtx-3080-ventus-3x-10g-oc-10gb-grafikkarte-13689638"
      - 
        name: "3080 MSI Gaming X"
        url: "https://www.digitec.ch/fr/s1/product/msi-geforce-rtx-3080-gaming-x-trio-10g-10gb-grafikkarte-13689639"